In [1]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv('/home/jan/Documents/Trainingsdaten/CT-Analyse_QualiPro_ZP_4/Porenanalyse_Porositäts-Hotspots_ZP4_17.12.2019.csv', delimiter =';')

In [8]:
data

,Position x [mm],Position y [mm],Position z [mm],Volumen [mm³],Oberfläche [mm²],Mittlere Porosität [%],Porositätsabweichung [%],Maximale Porosität [%],Beschreibung,Bild,Fokussiertes Bild,Screenshots
0,"3,3770","-0,2932","79,4013","0,00","0,08","2,03","0,02","2,07",NaN,Aus,Aus,0
1,"3,3192","-0,0074","77,3140","0,06","1,41","2,21","0,19","2,80",NaN,Aus,Aus,0
2,"3,2854","0,0072","59,8078","0,00","0,16","2,03","0,02","2,08",NaN,Aus,Aus,0
3,"3,2752","0,0553","66,9683","0,04","0,91","2,25","0,18","2,71",NaN,Aus,Aus,0
4,"3,2638","0,4990","67,0817","0,00","0,03","2,01","0,01","2,03",NaN,Aus,Aus,0
...,...,...,...,...,...,...,...,...,...,...,...,...
698,"-3,2387","-0,1565","60,4614","0,00","0,16","2,05","0,03","2,12",NaN,Aus,Aus,0
699,"-3,2512","-0,1373","76,9622","0,03","0,80","2,24","0,18","2,72",NaN,Aus,Aus,0
700,"-3,2563","0,3513","60,3218","0,00","0,13","2,04","0,03","2,10",NaN,Aus,Aus,0
701,"-3,3164","-0,5535","19,7093","0,01","0,42","2,09","0,06","2,26",NaN,Aus,Aus,0
702,"-3,3464","0,2941","21,3893","0,10","2,58","2,19","0,17","2,75",NaN,Aus,Aus,0