In [18]:
import os 
import pandas as pd
from shutil import copyfile, copy2

In [65]:
ZP_nummer = 9

In [66]:
ZP_csv = pd.read_csv('/home/jan/Documents/Trainingsdaten/ZPs/ZP{}/grid_size=874_threshold_porosity=125.csv'.format(ZP_nummer))
array_path = '/home/jan/Documents/Trainingsdaten/ZPs/ZP{}/1layer/Grid_size_874/'.format(ZP_nummer)
folder_pores = '/home/jan/Documents/Trainingsdaten/datasets/Grid_size_874_binary/porosity/'
folder_no_pores = '/home/jan/Documents/Trainingsdaten/datasets/Grid_size_874_binary/no_porosity/'

In [67]:
ZP_csv

       Unnamed: 0  Slice  x-grid  y-grid  Position  Poren  num Black pixels
0               0    376       0       0         0      1              1165
1               1    376       0       1         0      1               736
2               2    376       0       2         0      0                 0
3               3    376       1       0         0      0                 2
4               4    376       1       1         0      1               487
...           ...    ...     ...     ...       ...    ...               ...
10570       10570   1550       1       1         0      1               125
10571       10571   1550       1       2         0      0                 0
10572       10572   1550       2       0         0      0                 0
10573       10573   1550       2       1         0      0                 0
10574       10574   1550       2       2        -1      0                 0

[10575 rows x 7 columns]

In [68]:
for index,row in ZP_csv.iterrows():
    num_slice = row['Slice']
    x = row['x-grid']
    y = row['y-grid']
    Poren = row['Poren']
    src = array_path + 'Slice' + str("{:05d}".format(num_slice)) + '_x:' + str(x) + '_y:' + str(y) + '.npy'
    if os.path.isfile(src):
        if Poren == 0:
            dst = folder_no_pores + 'ZP{}_'.format(ZP_nummer) + 'Slice' + str("{:05d}".format(num_slice)) + '_x:' + str(x) + '_y:' + str(y) + '.npy'
                
        elif Poren == 1: 
            dst = folder_pores + 'ZP{}_'.format(ZP_nummer) + 'Slice' + str("{:05d}".format(num_slice)) + '_x:' + str(x) + '_y:' + str(y) + '.npy'
            
        copyfile(src, dst)